# will use a secret from vault kv engine that contains multiple keys. result will be a k8s secret with the keys from the vault secret. { "user": "bob", "password": "mypass" } will result in two keys user and password.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-find
  namespace: vault-kubernetes-auth
spec:
  secretStoreRef:
    name: vault-kubernetes-auth
    kind: SecretStore
  target:
    name: vault-find
  dataFrom:
    - find:
        path: vault-find
        name:
          regexp: ".*"
