apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kubernetes-auth
  namespace: vault-kubernetes-auth
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: vault-token-reviewer