# will use a secret from vault kv engine that contains multiple keys. result will be a k8s secret with the keys from the vault secret. { "user": "bob", "password": "mypass" } will result in two keys user and password.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-extracted
  namespace: vault-token-auth
spec:
  secretStoreRef:
    name: vault-token-auth
    kind: SecretStore
  target:
    name: vault-extracted
  dataFrom:
    - extract:
        key: vault-extracted