apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-token-auth
  namespace: vault-token-auth
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"